// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialTelemetry.Api.Infrastructure.Persistence;

#nullable disable

namespace SocialTelemetry.Api.Infrastructure.Persistence.Migrations.Sqlite
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008221636_AddAttachmentTranscripts")]
    partial class AddAttachmentTranscripts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.AnalysisConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InteractionAnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InteractionAnalysisId");

                    b.ToTable("AnalysisConversationMessages");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.AttachmentTranscript", b =>
                {
                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectedText")
                        .HasMaxLength(120000)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GeneratedText")
                        .HasMaxLength(120000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ReviewedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceStorageKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TranscriptionVersion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("AttachmentId");

                    b.ToTable("AttachmentTranscripts", t =>
                        {
                            t.HasCheckConstraint("CK_AttachmentTranscripts_CorrectedText_Length", "length(\"CorrectedText\") <= 120000");

                            t.HasCheckConstraint("CK_AttachmentTranscripts_GeneratedText_Length", "length(\"GeneratedText\") <= 120000");

                            t.HasCheckConstraint("CK_AttachmentTranscripts_Model_Length", "length(\"Model\") <= 200");

                            t.HasCheckConstraint("CK_AttachmentTranscripts_Provider_Length", "length(\"Provider\") <= 200");

                            t.HasCheckConstraint("CK_AttachmentTranscripts_SourceSha256_Length", "length(\"SourceSha256\") <= 64");

                            t.HasCheckConstraint("CK_AttachmentTranscripts_SourceStorageKey_Length", "length(\"SourceStorageKey\") <= 32");

                            t.HasCheckConstraint("CK_AttachmentTranscripts_TranscriptionVersion_Length", "length(\"TranscriptionVersion\") <= 200");
                        });
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.Interaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserThoughts")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Interactions");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.InteractionAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InteractionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InteractionId");

                    b.ToTable("InteractionAnalyses", t =>
                        {
                            t.HasCheckConstraint("CK_InteractionAnalyses_ContextFingerprint_Length", "length(\"ContextFingerprint\") <= 64");

                            t.HasCheckConstraint("CK_InteractionAnalyses_PromptVersion_Length", "length(\"PromptVersion\") <= 64");

                            t.HasCheckConstraint("CK_InteractionAnalyses_ResultJson", "\"ResultJson\" IS NULL OR json_valid(\"ResultJson\")");
                        });
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.InteractionAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InteractionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("StorageKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextContent")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InteractionId");

                    b.ToTable("InteractionAttachments");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.InteractionParticipant", b =>
                {
                    b.Property<Guid>("InteractionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.HasKey("InteractionId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("InteractionParticipants");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.People.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ArchivedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarMimeType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarStorageKey")
                        .IsConcurrencyToken()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("HowWeMet")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipContext")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("People", t =>
                        {
                            t.HasCheckConstraint("CK_People_AvatarMimeType_Length", "length(\"AvatarMimeType\") <= 32");

                            t.HasCheckConstraint("CK_People_AvatarStorageKey_Length", "length(\"AvatarStorageKey\") <= 32");

                            t.HasCheckConstraint("CK_People_DisplayName_Length", "length(\"DisplayName\") <= 200");

                            t.HasCheckConstraint("CK_People_RelationshipContext_Length", "length(\"RelationshipContext\") <= 32");
                        });
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.People.PersonExternalConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUserId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Handle")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "Platform", "ExternalUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_PersonConnection_StableIdentity");

                    b.ToTable("PersonExternalConnections", t =>
                        {
                            t.HasCheckConstraint("CK_PersonExternalConnections_DisplayName_Length", "length(\"DisplayName\") <= 200");

                            t.HasCheckConstraint("CK_PersonExternalConnections_ExternalUserId_Length", "length(\"ExternalUserId\") <= 128");

                            t.HasCheckConstraint("CK_PersonExternalConnections_Handle_Length", "length(\"Handle\") <= 200");

                            t.HasCheckConstraint("CK_PersonExternalConnections_Platform_Length", "length(\"Platform\") <= 32");

                            t.HasCheckConstraint("CK_PersonExternalConnections_ProfileUrl_Length", "length(\"ProfileUrl\") <= 2048");
                        });
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.People.PersonFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonFacts");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.People.PersonInference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceInteractionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("SourceInteractionId");

                    b.ToTable("PersonInferences");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.People.SuggestedProfileUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AcceptedValue")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InteractionAnalysisId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReviewedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InteractionAnalysisId");

                    b.HasIndex("PersonId");

                    b.ToTable("SuggestedProfileUpdates", t =>
                        {
                            t.HasCheckConstraint("CK_SuggestedProfileUpdates_Status_Length", "length(\"Status\") <= 16");
                        });
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AboutMe")
                        .HasColumnType("TEXT");

                    b.Property<string>("AiInstructions")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarMimeType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarStorageKey")
                        .IsConcurrencyToken()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Boundaries")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommunicationStyle")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Goals")
                        .HasColumnType("TEXT");

                    b.Property<string>("Preferences")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles", t =>
                        {
                            t.HasCheckConstraint("CK_UserProfiles_AvatarMimeType_Length", "length(\"AvatarMimeType\") <= 32");

                            t.HasCheckConstraint("CK_UserProfiles_AvatarStorageKey_Length", "length(\"AvatarStorageKey\") <= 32");
                        });
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Users.UserProfileExternalConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUserId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Handle")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId", "Platform", "ExternalUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserConnection_StableIdentity");

                    b.ToTable("UserProfileExternalConnections", t =>
                        {
                            t.HasCheckConstraint("CK_UserProfileExternalConnections_DisplayName_Length", "length(\"DisplayName\") <= 200");

                            t.HasCheckConstraint("CK_UserProfileExternalConnections_ExternalUserId_Length", "length(\"ExternalUserId\") <= 128");

                            t.HasCheckConstraint("CK_UserProfileExternalConnections_Handle_Length", "length(\"Handle\") <= 200");

                            t.HasCheckConstraint("CK_UserProfileExternalConnections_Platform_Length", "length(\"Platform\") <= 32");

                            t.HasCheckConstraint("CK_UserProfileExternalConnections_ProfileUrl_Length", "length(\"ProfileUrl\") <= 2048");
                        });
                });

            modelBuilder.Entity("SocialTelemetry.Api.Infrastructure.Persistence.AnalysisContextGuard", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserProfileId");

                    b.ToTable("AnalysisContextGuards", (string)null);
                });

            modelBuilder.Entity("SocialTelemetry.Api.Infrastructure.Persistence.StorageDatabaseIdentity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StorageDatabaseIdentity", null, t =>
                        {
                            t.HasCheckConstraint("CK_StorageDatabaseIdentity_Singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.AnalysisConversationMessage", b =>
                {
                    b.HasOne("SocialTelemetry.Api.Domain.Interactions.InteractionAnalysis", "InteractionAnalysis")
                        .WithMany("ConversationMessages")
                        .HasForeignKey("InteractionAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InteractionAnalysis");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.AttachmentTranscript", b =>
                {
                    b.HasOne("SocialTelemetry.Api.Domain.Interactions.InteractionAttachment", "Attachment")
                        .WithOne()
                        .HasForeignKey("SocialTelemetry.Api.Domain.Interactions.AttachmentTranscript", "AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attachment");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.Interaction", b =>
                {
                    b.HasOne("SocialTelemetry.Api.Domain.Users.UserProfile", "UserProfile")
                        .WithMany("Interactions")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.InteractionAnalysis", b =>
                {
                    b.HasOne("SocialTelemetry.Api.Domain.Interactions.Interaction", "Interaction")
                        .WithMany("Analyses")
                        .HasForeignKey("InteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interaction");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.InteractionAttachment", b =>
                {
                    b.HasOne("SocialTelemetry.Api.Domain.Interactions.Interaction", "Interaction")
                        .WithMany("Attachments")
                        .HasForeignKey("InteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interaction");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.InteractionParticipant", b =>
                {
                    b.HasOne("SocialTelemetry.Api.Domain.Interactions.Interaction", "Interaction")
                        .WithMany("Participants")
                        .HasForeignKey("InteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialTelemetry.Api.Domain.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interaction");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.People.Person", b =>
                {
                    b.HasOne("SocialTelemetry.Api.Domain.Users.UserProfile", "UserProfile")
                        .WithMany("People")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.People.PersonExternalConnection", b =>
                {
                    b.HasOne("SocialTelemetry.Api.Domain.People.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.People.PersonFact", b =>
                {
                    b.HasOne("SocialTelemetry.Api.Domain.People.Person", "Person")
                        .WithMany("Facts")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.People.PersonInference", b =>
                {
                    b.HasOne("SocialTelemetry.Api.Domain.People.Person", "Person")
                        .WithMany("Inferences")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialTelemetry.Api.Domain.Interactions.Interaction", "SourceInteraction")
                        .WithMany()
                        .HasForeignKey("SourceInteractionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Person");

                    b.Navigation("SourceInteraction");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.People.SuggestedProfileUpdate", b =>
                {
                    b.HasOne("SocialTelemetry.Api.Domain.Interactions.InteractionAnalysis", "InteractionAnalysis")
                        .WithMany()
                        .HasForeignKey("InteractionAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialTelemetry.Api.Domain.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InteractionAnalysis");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Users.UserProfileExternalConnection", b =>
                {
                    b.HasOne("SocialTelemetry.Api.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.Interaction", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("Attachments");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.InteractionAnalysis", b =>
                {
                    b.Navigation("ConversationMessages");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.People.Person", b =>
                {
                    b.Navigation("Facts");

                    b.Navigation("Inferences");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Users.UserProfile", b =>
                {
                    b.Navigation("Interactions");

                    b.Navigation("People");
                });
#pragma warning restore 612, 618
        }
    }
}
