// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SocialTelemetry.Api.Infrastructure.Persistence;

#nullable disable

namespace SocialTelemetry.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.AnalysisConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InteractionAnalysisId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InteractionAnalysisId");

                    b.ToTable("AnalysisConversationMessages");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.Interaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserThoughts")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Interactions");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.InteractionAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InteractionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InteractionId");

                    b.ToTable("InteractionAnalyses");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.InteractionAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InteractionId")
                        .HasColumnType("uuid");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.Property<string>("StorageKey")
                        .HasColumnType("text");

                    b.Property<string>("TextContent")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InteractionId");

                    b.ToTable("InteractionAttachments");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.InteractionParticipant", b =>
                {
                    b.Property<Guid>("InteractionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.HasKey("InteractionId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("InteractionParticipants");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.People.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("HowWeMet")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RelationshipContext")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.People.PersonFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonFacts");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.People.PersonInference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceInteractionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("SourceInteractionId");

                    b.ToTable("PersonInferences");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AboutMe")
                        .HasColumnType("text");

                    b.Property<string>("AiInstructions")
                        .HasColumnType("text");

                    b.Property<string>("Boundaries")
                        .HasColumnType("text");

                    b.Property<string>("CommunicationStyle")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Goals")
                        .HasColumnType("text");

                    b.Property<string>("Preferences")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.AnalysisConversationMessage", b =>
                {
                    b.HasOne("SocialTelemetry.Api.Domain.Interactions.InteractionAnalysis", "InteractionAnalysis")
                        .WithMany("ConversationMessages")
                        .HasForeignKey("InteractionAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InteractionAnalysis");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.Interaction", b =>
                {
                    b.HasOne("SocialTelemetry.Api.Domain.Users.UserProfile", "UserProfile")
                        .WithMany("Interactions")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.InteractionAnalysis", b =>
                {
                    b.HasOne("SocialTelemetry.Api.Domain.Interactions.Interaction", "Interaction")
                        .WithMany("Analyses")
                        .HasForeignKey("InteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interaction");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.InteractionAttachment", b =>
                {
                    b.HasOne("SocialTelemetry.Api.Domain.Interactions.Interaction", "Interaction")
                        .WithMany("Attachments")
                        .HasForeignKey("InteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interaction");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.InteractionParticipant", b =>
                {
                    b.HasOne("SocialTelemetry.Api.Domain.Interactions.Interaction", "Interaction")
                        .WithMany("Participants")
                        .HasForeignKey("InteractionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialTelemetry.Api.Domain.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interaction");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.People.Person", b =>
                {
                    b.HasOne("SocialTelemetry.Api.Domain.Users.UserProfile", "UserProfile")
                        .WithMany("People")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.People.PersonFact", b =>
                {
                    b.HasOne("SocialTelemetry.Api.Domain.People.Person", "Person")
                        .WithMany("Facts")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.People.PersonInference", b =>
                {
                    b.HasOne("SocialTelemetry.Api.Domain.People.Person", "Person")
                        .WithMany("Inferences")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocialTelemetry.Api.Domain.Interactions.Interaction", "SourceInteraction")
                        .WithMany()
                        .HasForeignKey("SourceInteractionId");

                    b.Navigation("Person");

                    b.Navigation("SourceInteraction");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.Interaction", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("Attachments");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Interactions.InteractionAnalysis", b =>
                {
                    b.Navigation("ConversationMessages");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.People.Person", b =>
                {
                    b.Navigation("Facts");

                    b.Navigation("Inferences");
                });

            modelBuilder.Entity("SocialTelemetry.Api.Domain.Users.UserProfile", b =>
                {
                    b.Navigation("Interactions");

                    b.Navigation("People");
                });
#pragma warning restore 612, 618
        }
    }
}
